### ISSUE TITLE
Use a different arg name in place of ``url``

### ISSUE THREAD

**Issue by valaparthvi** [ManageIQ/manageiq-api-client-python#45] opened 2019-03-22 20:40 UTC
While automating a manageiq test case for adding AnsibleTower via REST API, I encountered an issue.
Payload to add `AnsibleTower`
```
{
  "type": "ManageIQ::Providers::AnsibleTower::Provider",
  "url": ":url",
  "name": "API test",
  "verify_ssl": "false",
  "credentials": {
    "userid": ":userid",
    "password": ":password"
  }
}
```
API endpoint: `https://<ip_address>/api/providers?provider_class=provider`

I used `appliace.rest_api.post(endpoint_href, **payload)` to add the provider.
But I encountered `TypeError: post() got multiple values for keyword argument 'url'`error, reason being  -  `post` method expects a keyword argument called `url`, but since there is a keyword named `url` present in the payload, it throws error on unpacking.

There might be other API endpoints that may expect `url` in the payload, in which case, actions such as `post` would fail.

To avoid such conflicts, it might be a good idea to change the name of `url` to something like `endpoint_url` or `endpoint_href`. I don't think this change will affect any other part of the framework.

**Comment by cben** [comment] 2019-03-24 20:52
Good point!
Need to think if it's backward compatible - there might be code currently passing endpoint by url= name?

**Comment by valaparthvi** [comment] 2019-03-25 11:24
If you're talking about the framework itself, I don't think to change the arg_name would cause any trouble. I am not sure what other projects use this library, but I checked the manageiq/integration_tests and we have very rarely explicitly mentioned `url=` to pass the URL, but I can handle that.
I am not sure I completely understood what you wanted to say, so correct me if I misunderstood.

**Comment by mkoura** [comment] 2019-03-26 13:02
@valaparthvi @cben From https://github.com/ManageIQ/integration_tests pov it should not be a problem. However it is used also in Ansible (see e.g. [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/manageiq.py) and [here](https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/remote_management/manageiq)).
It's hard to tell if it breaks anything. To be on a safe side, how about smtg like

```python
def post(self, endpoint_url="_unchanged", **payload):
    if endpoint_url == "_unchanged":
        if "url" not in payload:
            raise ValueError("'endpoint_url' or 'url' key in payload needs to be specified")
        endpoint_url = payload.pop("url")
    ...
```
Not nice, but fully backward compatible (including situations when `None` is passed for url etc.)

**Comment by valaparthvi** [comment] 2019-03-26 14:26
Okay, so is this how a method would look like? :
```
def post(self, endpoint_url="_unchanged", **payload):
    if endpoint_url == "_unchanged":
        if "url" not in payload:
            raise ValueError("'endpoint_url' or 'url' key in payload needs to be specified")
        endpoint_url = payload.pop("url")
    
    self.logger.info("[RESTAPI] POST %s %r", endpoint_url, payload)
    data = self._sending_request(
        partial(self._session.post, endpoint_url, data=json.dumps(payload)))
    self.logger.info("[RESTAPI] RESPONSE %s", data)
    return self._result_processor(data)
```

Btw, if you don't mind, I'd like to work on this issue. Let me know.

**Comment by mkoura** [comment] 2019-03-26 14:35
@valaparthvi Yes. I'd say go ahead and do it like this, unless you or @cben have some better idea.

**Comment by valaparthvi** [comment] 2019-03-26 14:49
I like your workaround. However, I think sending URL in the payload might not be the best practice. We should only use `endpoint_url` when there is no choice, like the situation I mentioned in the issue. We should maintain the habit of using `url` to pass the URL. I don't think there is a sure-shot way to make sure this practice is followed, but adding a comment will help.

But I'll wait and see what @cben has to say about the workaround.

**Comment by mkoura** [comment] 2019-03-26 15:38
@valaparthvi Not sure I follow. We need to rename the `url` attribute because its name can clash with keys in payload. However if someone somewhere used it like `client.post(url=some_url, **payload)`, then this workaround will work for him (his `url` will become part of `payload`, gets popped from payload and used for `endpoint_url`). If we just renamed the argument, he would get `TypeError` about unexpected keyword argument 'url'. Does it make sense?

**Comment by valaparthvi** [comment] 2019-03-27 07:22
@mkoura I completely understand the workaround that you suggested. All I was saying, I will add a comment about the new `endpoint_url`, it's presence can be a little confusing otherwise.

**Comment by cben** [comment] 2019-04-01 14:30
Yeah, that's exactly the workaround I also thought of but didn't mention in hope one of you had better ideas :-)

- What if in future some manageiq api accepts a key called `endpoint_url`?  Unlikely, but I think given the method  accepts arbitrary keywords by design, it's reasonable to decide one is not supposed to pass the endpoint param by name at all, only positionally.

  You can reinforce this by naming the param something "internal" like `_url` to discourage passing it by name; or could really enforce it via `def post(self, *positional_url, **payload):` and checking whether `positional_url` is array of size 0 or 1 but that's too much work imho...

- Consider same treatment to the sibling methods `.get()`, `put()` etc, for consistency.

----

I do suspect it's fine to just break compatibility here and bump to v0.6.0.

- [x] checked ansible modules — they only pass url positionally.

let's see, does anybody else use this lib?  https://github.com/ManageIQ/manageiq-api-client-python/network/dependents, https://libraries.io/pypi/manageiq-client =>

- [x] https://github.com/StackStorm-Exchange/stackstorm-manageiq — only calls `client.delete()` with positional url.
- [x] https://github.com/ldomb/rhsummit2017 — seems to vendor an old version of ansible modules, and no longer interesting.
- [x] https://github.com/rhpit/manageiq-cli — doesn't call these methods (uses Collection interface)
- [ ] https://github.com/ManageIQ/integration_tests — guess you know it better...
  - saw one `url=` here: https://github.com/ManageIQ/integration_tests/blob/c94723bf2bb7aebd66a1e5e8130fb76f2ff935c2/cfme/base/__init__.py#L88

**Comment by valaparthvi** [comment] 2019-04-02 09:48
@cben I think `*positional_url` and `**payload` is likely to cause more trouble than worth for.
Take these cases for example:
1. demo_api.get(url="xyz.com", payload)
2. demo_api.get("xyz.com", payload)
3. demo_api.get(payload) - url is passed in the `payload` with a key say `url` or `href` or `endpoint_url` or whatever name, we don't know.

I feel it might be a little complicated to obtain the desired url from these arguments.

I think going with the idea Martin suggested, and changing the name to `_url` or something that's likely not to be used as key for the `payload`, like you suggested, might be the way to go.

**Comment by valaparthvi** [comment] 2019-04-02 12:59
@cben @mkoura can you tell me a little about this [patch request method](https://github.com/ManageIQ/manageiq-api-client-python/blob/master/src/manageiq_client/api.py#L128)? Why is the payload `*args` and not `**kwargs`?

**Comment by mkoura** [comment] 2019-04-02 13:16
Hey @valaparthvi It's because the `patch` method accepts list of dictionaries instead of one dictionary. There can be multiple actions in single request, see http://manageiq.org/docs/reference/euwe/doc-REST_API/miq/index#editing-a-resource-via-the-patch-method.

**Comment by mkoura** [comment] 2019-04-12 16:45
Fixed by https://github.com/ManageIQ/manageiq-api-client-python/pull/46

**Closed as completed by mkoura** 2019-04-12 16:45 UTC
